create register user api [management-api]
future-architect/apidoor pull request #43
Opened 2021-10-26 02:54 UTC by saiton03

#7 ( #23 )

management-api にユーザーを追加する。

開発初期に用いるライトな認証方法としてbasic認証を想定している。

2021-11-10 05:25 UTC, saiton03 commented on sql/001_init.sql
> +    belongings TEXT,
所属を意図していましたが、"affiliation"の方がわかりやすいですね。
また、現段階では必要最低限なカラムだけで良いと思うため、一旦削除しようと思います。

2021-11-10 05:39 UTC, saiton03 commented on sql/001_init.sql
> +    login_password_hash TEXT not null,  /* pgcryptoのcrypt関数を使用 */
おっしゃる通りです。記述を忘れていました。
追加します。

2021-11-10 05:59 UTC, saiton03 commented on sql/001_init.sql
> +    account_id VARCHAR(32) primary key,
id serial primary key ,
account_id VARCHAR(32) not null unique,
の形にしようと思います。また、apiinfoの方もidをpkにします。

2021-11-10 06:41 UTC, saiton03 commented on sql/001_init.sql
> +    is_admin boolean not null default 0,
変更します。
is_adminだとbool値なので、permission_flagにします。

2021-11-17 07:52 UTC, gmidorii requested changes

2021-11-17 07:52 UTC, gmidorii commented on sql/001_init.sql
>  CREATE TABLE IF NOT EXISTS public.log_list
log_list テーブルにもサロゲートキーをつけておいてほしいです。

2021-11-17 07:52 UTC, gmidorii commented on sql/001_init.sql
> +    permission_flag VARCHAR(2) not null default 0,
VARCHAR 型に対して、デフォルトで数値になっているので、 `"00"` のほうが良いかなと思いました。

2021-11-17 08:16 UTC, gmidorii approved these changes

2021-11-17 08:16 UTC, merged